.github/workflows/check.yml
src/Makevars.win

Trying to get a successful build on R-universe.

Install Rust toolchain when installing on windows on GitHub Actions

---

DESCRIPTION
NEWS.md
README.md

Bump to 0.0.1

---

.devcontainer/devcontainer.json

Delete settings already configured in upstream.

Minor refactoring of devcontainer.json

---

LICENSE.note
src/rust/Cargo.toml
vignettes/prqlr.Rmd

Minor updates I forgot to make in #35.
- Update `LICENSE.note`
- `default-features = false` for prql-compiler
- Fix typo.

Follow up #35

---

DESCRIPTION
NEWS.md
R/compile.R
R/knitr-engine.R
Taskfile.yml
man/prql_compile.Rd
tests/testthat/test-compile.R
vignettes/knitr.Rmd

feat: `prql_compile`'s options can be set as `options`

---

R/compile.R
src/rust/Cargo.lock
src/rust/Cargo.toml
tests/testthat/test-compile.R

fix: more appropriate error messages for unsupported targets

---

NEWS.md
Taskfile.yml

- Update NEWS
- Add a task for to release to the Taskfile

chore: prepare prqlr 0.3.0 release

---

R/compile.R
man/prql_compile.Rd
tests/testthat/test-compile.R

refactor: remove special error handling of unsupported target name in R side

---

DESCRIPTION
vignettes/prqlr.Rmd

docs: add sqldf example

---

src/Makevars.win

fix: fix build on Windows Rust 1.70

---

.github/workflows/check.yml
Taskfile.yml
configure
configure.win

feat: add configure scripts

---

DESCRIPTION
Taskfile.yml
dev/generate-authors.R
inst/AUTHORS

build: add inst/AUTHORS and a script to update AUTHORS

---

src/Makevars
src/Makevars.win

chore: set `CARGO_BUILD_JOBS=2` if not NOT_CRAN=true

---

DESCRIPTION

chore: use CRAN suggested SystemRequirements

---

LICENSE.note
Taskfile.yml
dev/generate-license-note.R

chore: update LICENSE.note for vendoring

---

NEWS.md

docs: update NEWS about updating for CRAN policy

---

R/knitr-engine.R
README.Rmd
README.md
src/Makevars
src/Makevars.win
vignettes/knitr.Rmd

- Simplifying R file
- Minor updates of docs
- Makefile refactoring

refactor: some refactoring of R code and docs

---

NEWS.md

docs: add news about vendoring

---

.github/workflows/pkgdown.yml
.github/workflows/release-lib.yml

ci: add a workflow to upload lib binaries

---

NEWS.md
README.Rmd
README.md

docs: add notes about pre-built libraries

---

LICENSE.note
inst/AUTHORS

docs: update LICENSE.note and AUTHORS with extendr 0.6.0

---

DESCRIPTION
Taskfile.yml
tests/testthat/_snaps/compile.md

And update the Taskfile to be able to install the latest version of package from CRAN mirror.

fix(test): update snapshot with testthat 3.2.0

---

.github/workflows/check.yml
DESCRIPTION
src/rust/Cargo.lock
src/rust/Cargo.toml
tools/lib-sums.tsv

Also fixing the CI's checking condition.

chore: bump lib version to 0.9.1

---

.devcontainer/devcontainer.json

- Remove useless `name`
- Ensure install `xz-utils`
- `ghcr.io/eitsupi/devcontainer-features/go-task`'s version
- Make `updateContentCommand` to an object.
- Add `ghcr.io/rocker-org/devcontainer-features/r-history`

build(devcontainer): refactor devcontainer definition

---

.github/workflows/check.yml
.github/workflows/pkgdown.yml
tools/lib-sums.tsv

ci: Rust cache for R CMD check

---

.github/workflows/release-lib.yml

ci: bump actions/upload-artifact and actions/download-artifact from 3 to 4

---

configure
tools/prep-lib.R

Close #246
https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Specifying-Target-Triplets.html

feat(installation): support cross-compiling the R package via the `--host` option of the configure script

---

DESCRIPTION
LICENSE.note
NEWS.md
README.Rmd
README.md
dev/generate-authors.R
dev/generate-license-note.R
dev/vendoring.R

docs: no longer depends on `extendr` and `rextendr`

---

DESCRIPTION
R/compile.R
README.Rmd
README.md
man/prql_version.Rd
man/prqlr-package.Rd
tests/testthat/_snaps/compile.md
tests/testthat/test-compile.R

docs: replace `prql-compiler` to `prqlc`

---

src/Makevars.win

fix: libgcc_eh.a is needed on Windows

---

LICENSE.note
src/rust/Cargo.lock

chore: cargo update

---

LICENSE.note
README.md
inst/AUTHORS
src/rust/Cargo.lock
src/rust/Cargo.toml

by running `CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS=fallback cargo +nightly -Zmsrv-policy generate-lockfile --manifest-path src/rust/Cargo.toml`

chore: change msrv from 1.81.0 to 1.73.0

---

tests/testthat/setup.R

test: ensure `NOT_CRAN="true"` on GitHub Actions

---

.github/workflows/check.yml
.github/workflows/release-lib.yml
tools/lib-sums.tsv
tools/prep-lib.R

I confirmed working on `ghcr.io/r-hub/r-minimal/r-minimal:latest`

feat: support install linux-gnu bin lib
