- src/Makevars.win
In #5 I made a change to configure the toolchain in Windows on GitHub Actions, but found that this is ignored by the R-universe builder.
https://github.com/r-universe-org/build-and-check/blob/9abc4b490a8371d548f93a86ca653ef4cf79b1c5/action.yml#L111
> Install Rust toolchain when source installing on windows allways

- .github/workflows/check.yml
- vignettes/prqlr.Rmd
I simplified the query example using tidyquery in #16, but will revert to something closer to what it was before.
The difference from the previous one is the deletion of `filter num_flts > 3000`, that makes it incompatible with tidyquery because it uses the WITH clause.
```r
library(tidyquery)
library(nycflights13)
"
from flights
join side:left planes [tailnum]
filter (distance | in 200..300)
filter air_time != null
group [origin, dest] (
aggregate [
num_flts = count,
num_seats = (sum seats | round 0),
avg_delay = (average arr_delay | round 0)
]
)
filter num_flts > 3000
sort [-num_seats, avg_delay]
take 2
" |>
prql_to_sql() |>
query()
```
> Update example of using with tidyquery

- src/Makevars.win
Suggested by #5 and r-universe-org/help#219
> Update Makevars.win for switching Rust Windows toolchain from GNU to MSVC

- src/Makevars
- src/Makevars.win
See <https://github.com/r-rust/faq>.
> ## How to avoid writing in HOME
>
> CRAN has a policy:
>
>> packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory
>
> On most systems, the default cargo configuration keeps a cache in `~/.cargo`, which can be changed by setting the `CARGO_HOME` envvar when invoking cargo. The hellorust package does this in the [`Makevars`](https://github.com/r-rust/hellorust/blob/master/src/Makevars) file.
> Update the `Makevars` files not to write files in user's HOME directory

- DESCRIPTION
- NEWS.md
- src/Makevars
- src/Makevars.win
Because `CARGO_HOME` was not exported, `prqlr` was writing `~/.cargo`.
After making this change I installed on a Docker container and verified that `~/.cargo` was not generated.
> Ensure change `CARGO_HOME` to temp dir

- .devcontainer/devcontainer.json
- Use the new `ghcr.io/rocker-org/devcontainer-features/r-packages` Feature to install R packages.
- Remove `terminal.integrated.defaultProfile.linux` vscode setting in favor of users' choise.
- Remove useless `remoteUser` property.
> chore: Update devcontainer.json

- .Rbuildignore
- dev/generate-license-note.R
Scripts used only during development should not be included after the build.
> Move the script for development to `dev` directory

- .devcontainer/devcontainer.json
If `Cargo.toml` does not exist in the project root, rust-analyzer will not work properly without this setting.
> Add setting for rust-analyzer in VS Code

- DESCRIPTION
Remove packages from Suggests that are not needed for package builds and tests.
> Remove `rextendr` and `lintr` from Suggests

- src/rust/Cargo.lock
- src/rust/Cargo.toml
> Use the fork's URL to install prql-compiler 0.4.0 to support Rust 1.61 (Ubuntu LTS) and 1.64 (Debian testing)

- DESCRIPTION
We can install these packages via `remotes::install_deps(dependencies = "config/needs/dev")`.
> Add Config/Needs/dev field and Config/Needs/website to DESCRIPTION

- DESCRIPTION
- R/knitr-engine.R
- R/zzz.R
- tests/testthat/_snaps/knitr-engine.md
- tests/testthat/files/test-engine.Rmd
- tests/testthat/test-knitr-engine.R
- vignettes/in_rmarkdown.Rmd
Enables PRQL engine for knitr that wraps knitr's SQL engine.
> Add PRQL engine for knitr

- .github/workflows/check-rust.yml
- src/rust/Cargo.toml
Close #50
Also set the `package.rust-version` field to Cargo.toml.
> ci: set workflow for check 'Minimum Supported Rust Version'

- Taskfile.yml
- Change to run potentially conflicting dependencies in order in `cmds`.
- Mark internal tasks.
- Fix regex.
> chore: some fixes for Taskfile.yml

- R/knitr-engine.R
- tests/testthat/_snaps/knitr-engine.md
- tests/testthat/files/minimal.Rmd
- tests/testthat/test-knitr-engine.R
If this change is not made, the display will be broken when `prqlr.format=FALSE` is set in the options.
> fix: ensure `format=TURE` in knitr engine

- src/Makevars
- src/Makevars.win
This change reduces build time during development.
> chore: not to remove `src/rust/target/release/build` during development

- src/rust/Cargo.lock
- src/rust/Cargo.toml
`anyhow` is no longer imported in prqlr.
> refactor: remove unused dependencies

- LICENSE.note
- NEWS.md
- src/rust/Cargo.lock
- src/rust/Cargo.toml
This version of extendr-api contains arm64 Linux support.
Fix #88
> fix: bump extendr-api and libR-sys to 0.4.0 for supporting arm64 Linux

- NEWS.md
- src/rust/Cargo.toml
Fix #91
It will be able to build with CRAN's arm64 mac builder (Rust 1.62 now) and Posit Package Manager's Ubuntu builder (Rust 1.61 now).
> fix: update `package.rust_version` to 1.60 (MSRV from csv v1.2.0)

- src/rust/Cargo.lock
- src/rust/Cargo.toml
The prql-compiler download fails in the test on macOS in #103, probably because I specified a commit on a PR from a fork in #101.
This PR switches to installation from the main branch, which should solve the problem in #103.
> chore: install prql-compiler from the latest commit

- NEWS.md
- README.md
- src/rust/Cargo.lock
- src/rust/Cargo.toml
Debian is still on Rust 1.63, so will switch to installing `prql-compiler` from the fork in order to pass the CRAN check.
> chore: support Rust 1.60

- DESCRIPTION
- dev/generate-license-note.R
Remove `dplyr` and `data.table` from the dev dependencies.
> build: refactor the generate-license-note script

- tests/testthat/test-knitr-engine.R
This is to disable `<div class="knitsql-table"></div>` in the output. Otherwise the change https://github.com/yihui/knitr/commit/10dd4c3d7f7f861175cf250f4f187505bf1039b0 will introduce the `<div>` (e.g., https://github.com/yihui/knitr-examples/commit/cd01db7a65413dfdde7cb2d89fa68faccafd20e0) due to https://github.com/yihui/knitr/blob/5ce55318ccb0e4b8dd15fba954e4503b7cb31a0f/R/engine.R#L669.
I'm not sure if you have plans for a new CRAN release in the near future. If you don't, I'll think about a workaround in **knitr** to avoid breaking your tests on CRAN. Thanks!
> test(knitr): Set options(knitr.sql.html_div = FALSE) for tests

- Taskfile.yml
I noticed that when `postCreateCommand` is executed, pak misses `cargo` and `rustc` (rextendr's system requirements) and try to install them via apt.
Off course they are already installed and should not install them via apt.
> chore: should not install cargo and rustc via apt in devcontainer

- NEWS.md
- src/Makevars
- src/Makevars.win
Part of #148
This is needed to avoid source code checking like:
```
* checking line endings in C/C++/Fortran sources/headers ... NOTE
Found the following sources/headers with CR or CRLF line endings:
src/rust/vendor/stacker/src/arch/windows.c
Some Unix compilers require LF line endings.
```
> chore: should remove the vendor dir on CRAN

- DESCRIPTION
- NEWS.md
- dev/generate-authors.R
- inst/AUTHORS
Related to #168
Addressing an email received after the first submission of prqlr 0.5.2 (#167).
> Thanks, we see:
>
>
>      person(given = "The authors of the dependency Rust crates", role = c("aut"),
>             comment = "see inst/AUTHORS file for details"))
>
> is not acceptable, especially as the file has things like
>
>
> ```
> addr2line (version 0.21.0):
>   addr2line authors
>
> anstyle (version 1.0.2):
>   anstyle authors
>
> anstyle-parse (version 0.2.1):
>   anstyle-parse authors
>
> anstyle-query (version 1.0.0):
>   anstyle-query authors
>
> anstyle-wincon (version 1.0.2):
>   anstyle-wincon authors
>
> is-terminal (version 0.4.9):
>   softprops, Dan Gohman
>
> itertools (version 0.10.5):
>   bluss
>
> itertools (version 0.11.0):
>   bluss
> ```
>
>
> Please fix and …
> docs: update AUTHORS format

- DESCRIPTION
- NEWS.md
- R/knitr-engine.R
> chore: remove the internal function `.get_engine_opt` in favor of the new feature of knitr 1.44

- .Rbuildignore
- .gitignore
- configure
- configure.win
- src/Makevars
- src/Makevars.ucrt
- src/Makevars.win
Also, remove the unnecessary `Makevars.ucrt` file. (The file was needed for R for Windows < 4.2)
> build(installation): allow installing with pre compiled libraries

- LICENSE.note
- src/rust/Cargo.lock
- src/rust/Cargo.toml
Related to #189
From now on, I will synchronize the Rust library version with prql-compiler.
This PR also includes updates to LICENSE.note, which had not been updated in #180.
> chore: set lib version to the Cargo.toml and update LICENSE.note

- .github/workflows/check.yml
- .github/workflows/release-lib.yml
`devtools::test`'s exit code always 0 (r-lib/testthat#515). So I shoud use `testthat::test("tests")` here instead.
And, `force=TRUE` should be set to `remotes::install_local`.
> ci: should stop if the tests are failed

- dev/generate-lib-sums.R
Version numbers should be ordered as `numeric_version`.
> build: fix the order of version number

- .github/workflows/check.yml
- .github/workflows/pkgdown.yml
- .github/workflows/release-lib.yml
Enable Rust cache on release-lib workflow and pkgdown workflow.
> ci: fix some Rust cache steps on some GitHub Actions workflows

- configure
When execute `Sys.setenv(LIBPRQLR_BUILD="false"); devtools::check`, it shows `'Rscript' should not be used without a path -- see par. 1.6 of the manual`.
> fix(installation): 'Rscript' should not be used without a path

- configure
Before copying, we should make the directory.
> fix(installation): ensure the parent directory

- .github/workflows/release-lib.yml
A follow up for #236
I forgot to update the release job.
> ci: fix the release job to use actions/download-artifact@v4

- DESCRIPTION
- LICENSE.note
- NEWS.md
- R/000-wrappers.R
- configure
- inst/AUTHORS
- src/init.c
- src/rust/api.h
> fix: ensure report rustc version while installation process

- src/Makevars.in
- src/Makevars.win
Pointed out by https://github.com/yutannihilation/savvy/issues/355#issuecomment-2740111502
And, deletes the `C_clean` target that are deemed unnecessary.
> fix: ensure cleanup after the lib build
